
# This file controls the behavior of the local Supabase CLI.
# Values in this file will be used as defaults for the commands.
project_id = "clifbcngdktxcxlsiwol"

[functions]
[functions.whatsapp-web-connect]
verify_jwt = true

[functions.whatsapp-qr-generate]
verify_jwt = true

[functions.whatsapp-qr-status]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = true
